### PR TITLE
Adds MATC branding

### LINKED ISSUE #94: Add MATC seal to the navigation bar
The full-size MATC seal image can be found in the project files in Teams. (Or just [click here](https://sumail.sharepoint.com/:i:/r/sites/LITFellowsClinic/Shared%20Documents/MATC%20small%20claims%20complaint/[Mass-Trial-Court-Seal-final-color.png](https://sumail.sharepoint.com/:i:/r/sites/LITFellowsClinic/Shared%20Documents/MATC%20small%20claims%20complaint/Mass-Trial-Court-Seal-final-color.png?csf=1&web=1&e=6jbCLv)?csf=1&web=1&e=6jbCLv).)

### PR DESCRIPTION
**Pull request by samglover**
This PR adds the MATC logo, colors, and border styles. Closes #94 

I used the logo and colors from Mass.gov, since that's where the resource link leads. For example, [here is the small claims resource page](https://www.mass.gov/small-claims).

### CODE REVIEW

**Comment by nonprofittechy** [comment]
Can you add some screenshots with the look and feel? Also, I think this should be in a separate repository with all MATC styles and shared questions

**Comment by samglover** [comment]
> Can you add some screenshots with the look and feel? Also, I think this should be in a separate repository with all MATC styles and shared questions

I'm glad you asked. It looks like the theme is overriding some styles. E.g.,

Screenshot 2024-11-25 at 12 10 13 PM

Before I start fixing this, is this a known issue that's easy to resolve?

**Comment by nonprofittechy** [comment]
> > Can you add some screenshots with the look and feel? Also, I think this should be in a separate repository with all MATC styles and shared questions
> 
> I'm glad you asked. It looks like the theme is overriding some styles, like input and label alignments:
> 
> Screenshot 2024-11-25 at 12 10 13 PM
> Before I start fixing this, is this a known issue that's easy to resolve?

Did you use bootstrap.build to generate the actual theme file, or just the .scss file? 

I ask because I notice it's minified, which our compiler doesn't do. If you didn't already, use the ALDashboard to generate it instead, from the .scss file. That should probably fix the interface glitches. For some reason, bootstrap.build's compiler isn't just the standard Bootstrap compiler and it results in some Docassemble glitches.

**Comment by samglover** [comment]
> Did you use bootstrap.build to generate the actual theme file, or just the .scss file?

I used bootstrap.build, and followed the directions here: https://assemblyline.suffolklitlab.org/docs/components/ALThemeTemplate/overview/#creating-a-custom-css-theme-with-bootstrapbuild

So I downloaded bootstrap.min.css and included that in the features block.

**Comment by samglover** [comment]
OK, this looks proper, now. I realize the long-term solution here is to use a separate repo, but since I don't yet know how to do that I'd like to merge this now in order to show it to the MATC tomorrow at our check-in. I'll keep an issue open to make sure it becomes a branding package we can use on all the MATC interviews.

**Pull request merged**
